- name: Set the noproxy hosts
  vmware.vmware_rest.appliance_networking_noproxy:
    vcenter_hostname: "{{ system_settings_hostname | d(omit) }}"
    vcenter_password: "{{ system_settings_password | d(omit) }}"
    vcenter_username: "{{ system_settings_username | d(omit) }}"
    vcenter_validate_certs: "{{ system_settings_validate_certs | d(omit) }}"
    servers: "{{ system_settings_noproxy }}"
  when: "system_settings_noproxy is defined"
  notify: Restart ntpd

- name: Configure the proxy configuration
  vmware.vmware_rest.appliance_networking_proxy:
    vcenter_hostname: "{{ system_settings_hostname | d(omit) }}"
    vcenter_password: "{{ system_settings_password | d(omit) }}"
    vcenter_username: "{{ system_settings_username | d(omit) }}"
    vcenter_validate_certs: "{{ system_settings_validate_certs | d(omit) }}"
    enabled: "{{ item.enabled | mandatory }}"
    server: "{{ item.url | mandatory }}"
    port: "{{ item.port | mandatory }}"
    protocol: "{{ item.protocol | mandatory }}"
    state: "{{ item.state | d(omit) }}"
    username: "{{ item.username | d(omit) }}"
    password: "{{ item.password | d(omit) }}"
  loop: "{{ system_settings_proxy }}"
  notify: Restart ntpd
