---
name: Ansible Integration Test
on:  # yamllint disable-line rule:truthy
  pull_request:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  ansible_integration_test:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Update pip, git
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install podman

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: ansible_collections/cloud/vmware_ops

      - name: Run
        run: |
          make integration
        working-directory: ansible_collections/cloud/vmware_ops
        env:
          vcenter_hostname: ${{ secrets.vcenter_hostname }}
          vcenter_username: ${{ secrets.vcenter_username }}
          vcenter_password: ${{ secrets.vcenter_password }}
